server:
    port: 3000
eureka:
    client:
      service-url:
         defaultZone: http://user:123456@localhost:8762/eureka/
spring:
  application:
    name: zuul

zuul:
  ignored-patterns: /**/test  #排除路径中带test结尾的地址代理
  routes:
    test1:
      path: /api/c/**
      serviceId: test-consumer
    test2:
      path: /api/p/**
      serviceId: test-consumer
#禁用过滤器（zuul.过滤器SimpleClassName.filterType.disable=true）
  PreRequestFilter:
     pre:
       disable: true